services:
  php-apache:
    build:
      context: ./site
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./site:/var/www/html
    networks:
      - frontend_network
    environment:
      - CAPTCHA_SECRET=${CAPTCHA_SECRET}
      - CAPTCHA_SITE=${CAPTCHA_SITE}

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./site:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt  # Volume to store SSL certificates
    depends_on:
      - php-apache
    networks:
      - frontend_network
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS

volumes:
  certs:  # Volume for SSL certificates
    external: true

networks:
  frontend_network:
    driver: bridge
