version: '3.8'

services:
  php-apache:
    build:
      context: ./site
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./site:/var/www/html
    networks:
      - frontend_network
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./site:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - php-apache
    networks:
      - frontend_network
      - backend_network
    ports:
      - "80:80"

networks:
  frontend_network:
    driver: bridge
  backend_network:
    external: true
