version: '3.8'

services:
  php-apache:
    build:
      context: ./site
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/html
    networks:
      - frontend_network
      - backend_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./site:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - php-apache
    networks:
      - frontend_network
      - backend_network
    ports:
      - "80:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend_network:
    driver: overlay
  backend_network:
    external: true
